public class RegistrationNop {
    public static void main(String [] args ){
        System.out.println("Feature: Nopcommerce Registration");
        System.out.println("As a user i want check registration functionality of Nopcommerce.");
        System.out.println();
        System.out.println("Background: I am on nopcommerce registration page.");
        System.out.println("Given       I open the google chrome browser");
        System.out.println("When        I open the URL: https://demo.nopcommerce.com/register ");
        System.out.println("Then        I am on nopcommerce registration page");
        System.out.println();
        System.out.println("Scenario Outline: I should not be able to register with invalid data on mandatory field (*) of registration page");
        System.out.println("When              I enter first name <First Name>");
        System.out.println("And               I enter last name <Last Name>");
        System.out.println("And               I enter Email address <Email>");
        System.out.println("And               I enter Password <Password>");
        System.out.println("And               I enter Confirm Password <Confirm Password>");
        System.out.println("And               Click on Register button");
        System.out.println("Then              I can see an error message <Error message>");
        System.out.println("And               I am not able to register");
        System.out.println("Examples:");
        System.out.println("         |First Name|Last Name|      E-mail    |Password|Confirm Password|     Error message                        |");
        System.out.println("         |          |  Borad  |Boradm@gmail.com|mb@12345|    mb@12345    |Please enter First name                   |");
        System.out.println("         |   Maitri |         |Boradm@gmail.com|mb@12345|    mb@12345    |Please enter Last name                    |");
        System.out.println("         |   Maitri |  Borad  |                |mb@12345|    mb@12345    |Please enter E-mail                       |");
        System.out.println("         |   Maitri |  Borad  |Boradm@gmail.com|        |    mb@12345    |Password is required                      |");
        System.out.println("         |   Maitri |  Borad  |Boradm@gmail.com|mb@12345|                |Confirm Password is required              |");
        System.out.println("         |   Maitri |  Borad  |Boradm@gmail.com|mb@12345|    mb12345     |Password and Confirm password must be same|");
        System.out.println("         |   Maitri |  Borad  |Boradmgmail.com |mb@12345|    mb@12345    |Please enter valid e_mail                 |");
        System.out.println("         |   Maitri |  Borad  |Boradm@gmail.com|   123  |       123      |Password does not match criteria          |");
        System.out.println("         |          |         |                |        |                |Mandatory fields required                 |");
        System.out.println();
        System.out.println("Scenario: User can select only one radio button from Gender options");
        System.out.println("Given     I am on Gender label");
        System.out.println("When      I select \"male\" radio button");
        System.out.println("And       I select \"Female\" radio button");
        System.out.println("Then      I am able to select only one radio button at a sametime");
        System.out.println();
        System.out.println("Scenario Outline: I should be able to select Day, Month and Year from drop down list of Date of birth field");
        System.out.println("Given             I am on Date of Birth field");
        System.out.println("When              I select <Day>");
        System.out.println("And               I select <Month>");
        System.out.println("And               I select <Year>");
        System.out.println("Then              I am able to select Day, Month and Year");
        System.out.println("Examples:");
        System.out.println("        | Day | Month | Year |");
        System.out.println("        |  06 |   07  | 1995 |");
        System.out.println();
        System.out.println("Scenario: I should be able to check and uncheck the Newsletter box");
        System.out.println("Given     I am on Newsletter label on Option");
        System.out.println("And       I click on Newsletter's checkbox");
        System.out.println("And       I again click on newsletter's checkbox");
        System.out.println("Then      I am able to check and uncheck checkbox of newsletter");
        System.out.println();
        System.out.println("Scenario: I should be able to register with valid mandatory (*) field data on registration page");
        System.out.println("When      I enter First Name \"Maitri\"");
        System.out.println("And       I enter Last Name \"Borad\"");
        System.out.println("And       I enter E-mail \"Boradm@gmail.com\"");
        System.out.println("And       I enter Password \"mb@12345\"");
        System.out.println("And       I enter Confirm Password \"mb@12345\"");
        System.out.println("And       I click on registration button");
        System.out.println("Then      I am able to register successfully");
    }
}
